### PR TITLE
Add doc for serilog:minimum-level:override:

### PR DESCRIPTION
**Pull request by tsimbalar**
Documents issue #2 (implemented by serilog/serilog#888) that supports serilog/serilog#754 from appsettings

### CODE REVIEW

**Comment by tsimbalar** [comment]
If this is accepted, this should also probably end up in the wiki section of serilog/serilog (https://github.com/serilog/serilog/wiki/AppSettings)

**Comment by nblumhardt** [comment]
Looks great, thanks. Probably should also update the wiki, but it's probably okay for now if the README here is a superset of the overview there.

**Comment by tsimbalar** [comment]
Maybe the *AppSettings* section from Serilog should just be a link to the *serilog-settings-appsetting*'s README ? 
After all, it is no longer "included by default" in Serilog.

**Comment by nblumhardt** [comment]
:+1: the wiki in general is due for some modernisation. One direction we could go is to focus the wiki on being an introduction and pointers to reference material, rather than being the reference itself. I'm sure @merbla has some thoughts on this topic :-)

**Comment by tsimbalar** [comment]
also, I might be wrong, but the problem with the **wiki** is that one cannot issue PRs for it, so it's harder to accept contributions for improvements.

**Comment by tsimbalar** [comment]
I've just added that section to the Serilog wiki as well (now I have the power ✊ 💪  !) in here : https://github.com/serilog/serilog/wiki/AppSettings#adding-minimum-level-overrides

**Pull request merged**
